import pathlib

current_path = pathlib.Path(__file__).parent
ARTIFACT_PATH = f'{current_path}/pipeline.joblib'

TEST_REQUEST = {
    "periodo" : "2020-07-01",
    "precipitaciones": {
        'coquimbo': 2.863,
         'valparaiso': 3.278,
         'metropolitanaSantiago': 9.391,
         'oHiggins': 10.747,
         'maule': 15.208,
         'biobio': 44.79,
         'laAraucania': 93.734,
         'losRios':164.055
    },
    "pib": {
        'agropecuarioSilvicola': 246063402,
         'pesca': 658990364,
         'mineria': 136630734,
         'mineriaCobre': 120179215,
         'otrasMineria': 164515187,
         'industriaManufacturera':132143102,
         'alimentos': 340178603,
         'bebidasYTabaco': 166094283,
         'textil': 322548927,
         'maderasYMuebles': 765629098,
         'celulosa': 102931541,
         'refinacionPetroleo': 931990492,
         'quimica': 216543583,
         'mineralesNoMetalicos': 749235327,
         'productosMetalicos': 218742629,
         'electricidad': 333038258,
         'construccion': 775062878,
         'comercio': 100824382,
         'restaurantesHoteles': 225515553,
         'transporte': 590501637,
         'comunicaciones': 388098255,
         'serviciosFinancieros': 582859961,
         'serviciosEmpresariales': 12033407,
         'serviciosVivienda': 858538617,
         'serviciosPersonales': 152382141,
         'adminPublica': 537090521,
         'aCostoFactores': 110258124,
         'absoluto': 120212803,
    },
    "imacec":{
        'empalmado': 104.626,
         'produccionBienes': 103.402,
         'minero': 108.267,
         'industria': 103.467,
         'restoBienes': 99.0,
         'comercio': 96.6,
         'servicio': 107.45,
         'aCostoFactores': 104.851,
         'noMinero': 104.177,
    },
    "indiceVentasNoDurablesIVCM": 94.6
}

TEST_FEATURES = {
    'anho' : 2022,
    'mes': 6,
    'Coquimbo': 2.863,
         'Valparaiso': 3.278,
         'Metropolitana_de_Santiago': 9.391,
         'Libertador_Gral__Bernardo_O_Higgins': 10.747,
         'Maule': 15.208,
         'Biobio': 44.79,
         'La_Araucania': 93.734,
         'Los_Rios':164.055,
        'PIB_Agropecuario_silvicola': 246063402,
         'PIB_Pesca': 658990364,
         'PIB_Mineria': 136630734,
         'PIB_Mineria_del_cobre': 120179215,
         'PIB_Otras_actividades_mineras': 164515187,
         'PIB_Industria_Manufacturera':132143102,
         'PIB_Alimentos': 340178603,
         'PIB_Bebidas_y_tabaco': 166094283,
         'PIB_Textil': 322548927,
         'PIB_Maderas_y_muebles': 765629098,
         'PIB_Celulosa': 102931541,
         'PIB_Refinacion_de_petroleo': 931990492,
         'PIB_Quimica': 216543583,
         'PIB_Minerales_no_metalicos_y_metalica_basica': 749235327,
         'PIB_Productos_metalicos': 218742629,
         'PIB_Electricidad': 333038258,
         'PIB_Construccion': 775062878,
         'PIB_Comercio': 100824382,
         'PIB_Restaurantes_y_hoteles': 225515553,
         'PIB_Transporte': 590501637,
         'PIB_Comunicaciones': 388098255,
         'PIB_Servicios_financieros': 582859961,
         'PIB_Servicios_empresariales': 12033407,
         'PIB_Servicios_de_vivienda': 858538617,
         'PIB_Servicios_personales': 152382141,
         'PIB_Administracion_publica': 537090521,
         'PIB_a_costo_de_factores': 110258124,
         'PIB': 120212803,
        'Imacec_empalmado': 104.626,
         'Imacec_produccion_de_bienes': 103.402,
         'Imacec_minero': 108.267,
         'Imacec_industria': 103.467,
         'Imacec_resto_de_bienes': 99.0,
         'Imacec_comercio': 96.6,
         'Imacec_servicios': 107.45,
         'Imacec_a_costo_de_factores': 104.851,
         'Imacec_no_minero': 104.177,
    "Indice_de_ventas_comercio_real_no_durables_IVCM": 94.6
}


DATE_KEY = 'periodo'
MONTH_COL = 'mes'
YEAR_COL = 'anho'

REPLACE_COLS = {
        "precipitaciones_coquimbo": "Coquimbo",
         "precipitaciones_valparaiso": "Valparaiso",
         "precipitaciones_metropolitanaSantiago": "Metropolitana_de_Santiago",
         "precipitaciones_oHiggins": "Libertador_Gral__Bernardo_O_Higgins",
         "precipitaciones_maule": "Maule",
         "precipitaciones_biobio": "Biobio",
         "precipitaciones_laAraucania": "La_Araucania",
         "precipitaciones_losRios": "Los_Rios",
        "pib_agropecuarioSilvicola": "PIB_Agropecuario_silvicola",
         "pib_pesca": "PIB_Pesca",
         "pib_mineria": "PIB_Mineria",
         "pib_mineriaCobre": "PIB_Mineria_del_cobre",
         "pib_otrasMineria": "PIB_Otras_actividades_mineras",
         "pib_industriaManufacturera":"PIB_Industria_Manufacturera",
         "pib_alimentos": "PIB_Alimentos",
         "pib_bebidasYTabaco": "PIB_Bebidas_y_tabaco",
         "pib_textil": "PIB_Textil",
         "pib_maderasYMuebles": "PIB_Maderas_y_muebles",
         "pib_celulosa": "PIB_Celulosa",
         "pib_refinacionPetroleo": "PIB_Refinacion_de_petroleo",
         "pib_quimica": "PIB_Quimica",
         "pib_mineralesNoMetalicos": "PIB_Minerales_no_metalicos_y_metalica_basica",
         "pib_productosMetalicos": "PIB_Productos_metalicos",
         "pib_electricidad": "PIB_Electricidad",
         "pib_construccion": "PIB_Construccion",
         "pib_comercio": "PIB_Comercio",
         "pib_restaurantesHoteles": "PIB_Restaurantes_y_hoteles",
         "pib_transporte": "PIB_Transporte",
         "pib_comunicaciones": "PIB_Comunicaciones",
         "pib_serviciosFinancieros": "PIB_Servicios_financieros",
         "pib_serviciosEmpresariales": "PIB_Servicios_empresariales",
         "pib_serviciosVivienda": "PIB_Servicios_de_vivienda",
         "pib_serviciosPersonales": "PIB_Servicios_personales",
         "pib_adminPublica": "PIB_Administracion_publica",
         "pib_aCostoFactores": "PIB_a_costo_de_factores",
         "pib_absoluto": "PIB",
         "imacec_empalmado": "Imacec_empalmado",
         "imacec_produccionBienes": "Imacec_produccion_de_bienes",
         "imacec_minero": "Imacec_minero",
         "imacec_industria": "Imacec_industria",
         "imacec_restoBienes": "Imacec_resto_de_bienes",
         "imacec_comercio": "Imacec_comercio",
         "imacec_servicio": "Imacec_servicios",
         "imacec_aCostoFactores": "Imacec_a_costo_de_factores",
         "imacec_noMinero": "Imacec_no_minero",
        "indiceVentasNoDurablesIVCM": "Indice_de_ventas_comercio_real_no_durables_IVCM"
}

PIB_COLS = ['PIB_Agropecuario_silvicola', 'PIB_Pesca',
       'PIB_Mineria', 'PIB_Mineria_del_cobre', 'PIB_Otras_actividades_mineras',
       'PIB_Industria_Manufacturera', 'PIB_Alimentos', 'PIB_Bebidas_y_tabaco',
       'PIB_Textil', 'PIB_Maderas_y_muebles', 'PIB_Celulosa',
       'PIB_Refinacion_de_petroleo', 'PIB_Quimica',
       'PIB_Minerales_no_metalicos_y_metalica_basica',
       'PIB_Productos_metalicos', 'PIB_Electricidad', 'PIB_Construccion',
       'PIB_Comercio', 'PIB_Restaurantes_y_hoteles', 'PIB_Transporte',
       'PIB_Comunicaciones', 'PIB_Servicios_financieros',
       'PIB_Servicios_empresariales', 'PIB_Servicios_de_vivienda',
       'PIB_Servicios_personales', 'PIB_Administracion_publica',
       'PIB_a_costo_de_factores', 'PIB']

IMACEC_COLS = ['Imacec_empalmado', 'Imacec_produccion_de_bienes', 'Imacec_minero',
       'Imacec_industria', 'Imacec_resto_de_bienes', 'Imacec_comercio',
       'Imacec_servicios', 'Imacec_a_costo_de_factores', 'Imacec_no_minero']

IV_COL = 'Indice_de_ventas_comercio_real_no_durables_IVCM'

FINAL_COLS = [MONTH_COL, YEAR_COL] + PIB_COLS + IMACEC_COLS + [IV_COL]